output: main.o login.o customer_entry.o item_entry.o bill_generation.o
	gcc main.o login.o customer_entry.o item_entry.o bill_generation.o -o output

main.o: main.c
	gcc -c main.c

login.o: login.c
	gcc -c login.c

customer_entry.o: customer_entry.c
	gcc -c customer_entry.c

item_entry.o: item_entry.c
	gcc -c item_entry.c

bill_generation.o: bill_generation.c
	gcc -c bill_generation.c
